name: "test-cdflow"

on:
  push:
    branches:
      - master

jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - name: Install cdflow
        uses: mergermarket/cdflow-action@master

      - name: execute cdflow help
        run: ls -l
